import os
from pyproc import *
procOpts(nprocess=2)
FID('/Users/pipapa/Desktop/pab1/NMR/RRM3 NMR 022119/1')
CREATE('/Users/pipapa/Desktop/pab1/NMR/RRM3 NMR 022119/1/zggpw5.nv')
acqOrder('1')
acqarray(0)
fixdsp(True)
skip(0)
label('1H')
acqsize(0)
tdsize(0)
sf('SFO1,1')
sw('SW_h,1')
ref('')
DIM(1)
EXPD(lb=0.5)
ZF()
FT()
AUTOPHASE(firstOrder=True)
PHASE(ph0=-9.2,ph1=-6.5,dimag=False)
run()